/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_santiance_sdlbits_SDL */

#ifndef _Included_com_santiance_sdlbits_SDL
#define _Included_com_santiance_sdlbits_SDL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    initSDLbits
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_santiance_sdlbits_SDL_initSDLbits
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    initSubSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_initSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    quitSubSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_quitSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_quit
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    wasInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_wasInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_santiance_sdlbits_SDL_getError
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    clearError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_clearError
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getVideoSurface
 * Signature: ()Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_getVideoSurface
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getVideoInfo
 * Signature: ()Lcom/santiance/sdlbits/SDLVideoInfo;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_getVideoInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getVideoDriverName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_santiance_sdlbits_SDL_getVideoDriverName
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    listModes
 * Signature: (Lcom/santiance/sdlbits/SDLPixelFormat;I)[Lcom/santiance/sdlbits/SDLRect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_santiance_sdlbits_SDL_listModes
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    videoModeOK
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_videoModeOK
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setVideoMode
 * Signature: (IIII)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_setVideoMode
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    updateRect
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;IIII)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_updateRect
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    updateRects
 * Signature: ([Lcom/santiance/sdlbits/SDLRect;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_updateRects
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    flip
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_flip
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setColors
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;[I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_setColors
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setPalette
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;I[I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_setPalette
  (JNIEnv *, jclass, jobject, jint, jintArray);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setGamma
 * Signature: (FFF)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_setGamma
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    mapRGB
 * Signature: (Lcom/santiance/sdlbits/SDLPixelFormat;III)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_mapRGB
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    mapRGBA
 * Signature: (Lcom/santiance/sdlbits/SDLPixelFormat;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_mapRGBA
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    createRGBSurface
 * Signature: (IIIIIIII)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_createRGBSurface
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    createRGBSurfaceFrom
 * Signature: (Ljava/nio/ByteBuffer;IIIIIIII)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_createRGBSurfaceFrom
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    freeSurface
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_freeSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    lockSurface
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_lockSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    unlockSurface
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_unlockSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    convertSurface
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;Lcom/santiance/sdlbits/SDLPixelFormat;I)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_convertSurface
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    displayFormat
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_displayFormat
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    displayFormatAlpha
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_displayFormatAlpha
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    loadBMP
 * Signature: (Ljava/lang/String;)Lcom/santiance/sdlbits/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_loadBMP
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    saveBMP
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_saveBMP
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setColorKey
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;II)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_setColorKey
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setAlpha
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_setAlpha
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setClipRect
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;Lcom/santiance/sdlbits/SDLRect;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_setClipRect
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getClipRect
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;Lcom/santiance/sdlbits/SDLRect;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_getClipRect
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    blitSurface
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;Lcom/santiance/sdlbits/SDLRect;Lcom/santiance/sdlbits/SDLSurface;Lcom/santiance/sdlbits/SDLRect;)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_blitSurface
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    fillRect
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;Lcom/santiance/sdlbits/SDLRect;I)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_fillRect__Lcom_santiance_sdlbits_SDLSurface_2Lcom_santiance_sdlbits_SDLRect_2I
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    fillRect
 * Signature: (Lcom/santiance/sdlbits/SDLSurface;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_fillRect__Lcom_santiance_sdlbits_SDLSurface_2IIIII
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    gl_getAttribute
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_gl_1getAttribute
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    gl_setAttribute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_gl_1setAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    gl_swapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_gl_1swapBuffers
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    pumpEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_pumpEvents
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    pollEvent
 * Signature: ()Lcom/santiance/sdlbits/SDLEvent;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_pollEvent
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    pushEvent
 * Signature: (Lcom/santiance/sdlbits/SDLEvent;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_pushEvent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    setEventFilter
 * Signature: (Lcom/santiance/sdlbits/SDLEventFilter;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_setEventFilter
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    numJoysticks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_numJoysticks
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_santiance_sdlbits_SDL_joystickName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickOpen
 * Signature: (I)Lcom/santiance/sdlbits/SDLJoystick;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_joystickOpen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_joystickUpdate
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickOpened
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_santiance_sdlbits_SDL_joystickOpened
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickIndex
 * Signature: (Lcom/santiance/sdlbits/SDLJoystick;)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_joystickIndex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickNumButtons
 * Signature: (Lcom/santiance/sdlbits/SDLJoystick;)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_joystickNumButtons
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickNumAxes
 * Signature: (Lcom/santiance/sdlbits/SDLJoystick;)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_joystickNumAxes
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickGetButton
 * Signature: (Lcom/santiance/sdlbits/SDLJoystick;I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_joystickGetButton
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickGetAxis
 * Signature: (Lcom/santiance/sdlbits/SDLJoystick;I)I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_joystickGetAxis
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    joystickClose
 * Signature: (Lcom/santiance/sdlbits/SDLJoystick;)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_joystickClose
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    openAudio
 * Signature: (Lcom/santiance/sdlbits/SDLAudioSpec;)Lcom/santiance/sdlbits/SDLAudioSpec;
 */
JNIEXPORT jobject JNICALL Java_com_santiance_sdlbits_SDL_openAudio
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    pauseAudio
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_pauseAudio
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getAudioStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_getAudioStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    lockAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_lockAudio
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    unlockAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_unlockAudio
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    closeAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_closeAudio
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    mixAudio
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_mixAudio
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getTicks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_getTicks
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_delay
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    showCursor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_showCursor
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    isCursorVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_santiance_sdlbits_SDL_isCursorVisible
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getMouseState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_santiance_sdlbits_SDL_getMouseState
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getMouseX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_getMouseX
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getMouseY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_getMouseY
  (JNIEnv *, jclass);

/*
 * Class:     com_santiance_sdlbits_SDL
 * Method:    getMouseButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_santiance_sdlbits_SDL_getMouseButton
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
